name: BiteRename
version: '${version}'
main: gg.bitesize.rename.BiteRename
api-version: '26.3'
description: Rename items, edit lore, and save reusable templates.
author: bitesize
website: https://bitesize.gg

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:${kotlinVersion}
